import localFont from 'next/font/local';
import './globals.css';
import { Outfit } from 'next/font/google';

import { Toaster } from '@/components/ui/sonner';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const outfit = Outfit({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
