import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { AppProvider } from "./_context/AppContext";

export const metadata = {
  title: "Reddify",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body className={outfit.className}>
          <AppProvider className={outfit.className}>{children}</AppProvider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
